[package]
name = "tangra"
description = "🪵 A lightweight and easy to use Rust logging library"
version = "1.3.0"
edition = "2021"
license = "MIT"
readme = "README.md"

[dependencies]
chrono = "0.4.31"
whoami = "1.4.1"
